"""Initial migration

Revision ID: b3c0518dc3bb
Revises: 
Create Date: 2023-10-07 15:50:12.079457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c0518dc3bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_house', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
